# Generated by Django 4.1.6 on 2023-02-19 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Неполный трек', 'Неполный трек'), ('Не является треком', 'Не является треком'), ('Другое', 'Другое')], default=2, max_length=20)),
                ('description', models.TextField()),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.music')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
